---
title: "Nationalratswahlen 2023"
output: html_document
editor_options: 
  chunk_output_type: console
---

#### Load packages and data
```{r message=FALSE, warning=FALSE}
# Packages
library(tidyverse)
library(scales)
library(ggrepel)
theme_set(theme_minimal())

# Data
df <- readxl::read_xlsx(here::here("Data",
                                   "2023_10_22_Nationalratswahlen_2023_Budgetierte_Einnahmen_und_Zuwendungen.xlsx")) %>% 
  janitor::clean_names()
```

\
\

## Data processing

```{r message=FALSE, warning=FALSE}
# take a look first
glimpse(df)

# only dates need to be fixed
df <- df %>% 
  mutate(datum = as_date(datum, origin = "1900-01-01") - 2,
         datum_des_exports = dmy(datum_des_exports))

# handle names
df <- df %>% 
  # create short party names
  mutate(parteizugehorigkeit_mutterpartei_kurz = case_when(
    parteizugehorigkeit_mutterpartei == "Die Mitte" ~ "Mitte",
    parteizugehorigkeit_mutterpartei == "Eidgenössisch-Demokratische Union" ~ "EDU",
    parteizugehorigkeit_mutterpartei == "Evangelische Volkspartei der Schweiz" ~ "EVP",
    parteizugehorigkeit_mutterpartei == "FDP.Die Liberalen" ~ "FDP",
    parteizugehorigkeit_mutterpartei == "GRÜNE Schweiz" ~ "Grüne",
    parteizugehorigkeit_mutterpartei == "Grünliberale Partei" ~ "GLP",
    parteizugehorigkeit_mutterpartei == "Lega dei Ticinesi" ~ "Lega",
    parteizugehorigkeit_mutterpartei == "Schweizerische Volkspartei" ~ "SVP",
    parteizugehorigkeit_mutterpartei == "Sozialdemokratische Partei der Schweiz" ~ "SP",
    parteizugehorigkeit_mutterpartei == "Übrige politische Parteien" ~ "Übrige",
    TRUE ~ parteizugehorigkeit_mutterpartei)
  ) %>% 
  # create full name
  rename("nachname" = name) %>% 
  mutate(name = str_c(vorname, nachname, 
                      sep = " "),
         name = str_to_title(name))

# get the right party color
party_colors <- c(SVP = "#00A04F",
                  SP = "#E40326",
                  FDP = "#104FA0",
                  Mitte = "#F1920E",
                  Grüne = "#84B419",
                  GLP = "#49A3DE",
                  EVP = "#FFDD00",
                  Lega = "#1664B7",
                  EDU = "black",
                  Unabhängig = "grey30",
                  Übrige = "grey50")
```

\
\

## Analysis

\

### National Council

\

#### Which single person has the most money to spend for their campaign?
```{r message=FALSE, warning=FALSE}
# create smaller data frame
df_einzelperson <- df %>% 
  filter(kampagne_fur == "Einzelperson")

# plot
df_einzelperson %>% 
  mutate(name = fct_reorder(name, gesamtbetrag_der_einnahmen_in_chf)) %>%
  top_n(gesamtbetrag_der_einnahmen_in_chf, 
        n = 50) %>% 
  ggplot(aes(gesamtbetrag_der_einnahmen_in_chf, name)) + 
  geom_col(aes(fill = parteizugehorigkeit_mutterpartei_kurz)) + 
  geom_vline(xintercept = median(df_einzelperson$gesamtbetrag_der_einnahmen_in_chf),
             lty = 2,
             linewidth = 1.1,
             alpha = 0.5) + 
  geom_vline(xintercept = mean(df_einzelperson$gesamtbetrag_der_einnahmen_in_chf),
             lty = 1,
             linewidth = 1.1,
             alpha = 0.5) + 
  # geom_text(aes(label = format(gesamtbetrag_der_einnahmen_in_chf, 
  #                              big.mark = "`")),
  #           size = 3.5,
  #           hjust = -0.05,
  #           check_overlap = TRUE) + 
  scale_x_continuous(labels = comma_format(big.mark = "`"),
                     breaks = seq(0, 400000, 50000)) + 
  scale_fill_manual(values = party_colors) +
  labs(title = "\nWelche Einzelperson hat am meisten Geld für die jeweilige Wahlkampagne zur Verfügung?",
       subtitle = "Nationalratswahlen 2023\n",
       fill = "Partei:",
       x = "\nMenge an zur Verfügung stehendem Geld in CHF\n",
       y = "",
       caption = "Gestrichtelte Linie repräsentiert den Medianwert aller Einzelpersonen (76'000 CHF).\nDurchgezogene Linie repräsentiert den Durchschnittswert aller Einzelpersonen (~ 95'184.60 CHF).")
```

\ 

#### How is the money for the campaign made up?

```{r warning=FALSE, message=FALSE}
# crete temporary data frame
df_einzelperson_temp <- df_einzelperson %>% 
  mutate(`Monetare Zuwendungen` = einnahmen_durch_monetare_zuwendungen_in_chf /
           gesamtbetrag_der_einnahmen_in_chf,
         `Wert nicht monetarer Zuwendungen` = wert_der_einnahmen_durch_nichtmonetare_zuwendungen_in_chf /
           gesamtbetrag_der_einnahmen_in_chf,
         `Einnahmen Veranstaltungen` = einnahmen_durch_veranstaltungen_in_chf /
           gesamtbetrag_der_einnahmen_in_chf,
         `Einnahmen Güter und Dienstleistungen` = einnahmen_durch_den_verkauf_von_gutern_und_dienstleistungen_in_chf /
           gesamtbetrag_der_einnahmen_in_chf,
         `Eigenmittel` = monetare_eigenmittel_in_chf /
           gesamtbetrag_der_einnahmen_in_chf)

# get names in right order
ordered_names <- df_einzelperson_temp %>% 
  arrange(Eigenmittel) %>% 
  pull(name)

# reshape data
df_einzelperson_long <- df_einzelperson_temp %>% 
  pivot_longer(cols = `Monetare Zuwendungen`:`Eigenmittel`,
               names_to = "pct_variables",
               values_to = "pct_values")

# plot
df_einzelperson_long %>% 
  mutate(name = fct_relevel(name, ordered_names),
         pct_variables = fct_rev(pct_variables)) %>% 
  ggplot(aes(pct_values, name,
             fill = pct_variables)) + 
  geom_col(color = "white") +
  scale_x_continuous(labels = percent_format()) + 
  scale_fill_viridis_d(direction = -1) +
  labs(title = "\nWie setzt sich das Geld für die Wahlkampagne zusammen?",
       subtitle = "Nationalratswahlen 2023\n",
       x = "",
       y = "",
       fill = "",
       caption = "Nach abnehmenden Eigenmittel angeordnet.")
  
```



